pay_method_ids = {
    "QIWI RUB": "63",
    "Тинькофф RUB": "105",
    "Сбербанк RUB": "42"
}

pay_method_names = {
    '63': 'QIWI RUB',
    '105': 'Тинькофф RUB',
    '42': 'Сбербанк RUB'
}

crypto_ids = {
    'XMR': '149',
    'BTC': '93',
    'LTC': '99',
    'XLM': '182',
    'ETC': '160',
    'ZEC': '162',
    'DOT': '201',
    'QTUM': '26',
    'BUSD': '206',
    'DASH': '140',
    'DOGE': '115',
    # 'DAI': '203',
    'BCH': '172',
    'BTG': '184',
    'TUSD': '24',
    'PAX': '189',
    'XEM': '173',
    'REP': '174',
    'NEO': '177',
    'EOS': '178',
    # 'LSK': '180',
    'ADA': '181',
    'WAVES': '133',
    'OMG': '48',
    'XVG': '124',
    'ZRX': '168',
    'ICX': '104',
    'KMD': '134',
    'BTT': '27',
    'BAT': '61',
    'ONT': '135',
    'LINK': '197',
    'ATOM': '198',
    'XTZ': '175',
    'UNI': '202',
    'RVN': '205',
    'SOL': '82',
    'VET': '8',
    'ETH': '139',
    'TRX': '185',
    'BNB': '19'
}

crypto_names = {
    '149': 'XMR',
    '93': 'BTC',
    '99': 'LTC',
    '182': 'XLM',
    '160': 'ETC',
    '162': 'ZEC',
    '201': 'DOT',
    '26': 'QTUM',
    '206': 'BUSD',
    '140': 'DASH',
    '115': 'DOGE',
    # '203': 'DAI',
    '172': 'BCH',
    '184': 'BTG',
    '24': 'TUSD',
    '189': 'PAX',
    '173': 'XEM',
    '174': 'REP',
    '177': 'NEO',
    '178': 'EOS',
    #'180': 'LSK',
    '181': 'ADA',
    '133': 'WAVES',
    '48': 'OMG',
    '124': 'XVG',
    '168': 'ZRX',
    '104': 'ICX',
    '134': 'KMD',
    '27': 'BTT',
    '61': 'BAT',
    '135': 'ONT',
    '197': 'LINK',
    '198': 'ATOM',
    '175': 'XTZ',
    '202': 'UNI',
    '205': 'RVN',
    '82': 'SOL',
    '8': 'VET',
    '139': 'ETH',
    '185': 'TRX',
    '19': 'BNB'
}

bestchange_best_courses_layout = {
    '149': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '93': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '99': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '182': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '160': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '162': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '201': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '26': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '206': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '140': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '115': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    # '203': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '172': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '184': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '24': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '189': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '173': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '174': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '177': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '178': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    #'180': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '181': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '133': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '48': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '124': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '168': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '104': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '134': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '27': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '61': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '135': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '197': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '198': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '175': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '202': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '205': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '82': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '8': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '139': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '185': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308],
    '19': ['PAY_METHOD', 'PLATFORM_ID', 1.7976931348623157e+308]
}

binance_courses_to_usdt_layout = {
    'XMR': 'CURRENT_PRICE',
    'BTC': 'CURRENT_PRICE',
    'LTC': 'CURRENT_PRICE',
    'XLM': 'CURRENT_PRICE',
    'ETC': 'CURRENT_PRICE',
    'ZEC': 'CURRENT_PRICE',
    'DOT': 'CURRENT_PRICE',
    'QTUM': 'CURRENT_PRICE',
    'BUSD': 'CURRENT_PRICE',
    'DASH': 'CURRENT_PRICE',
    'DOGE': 'CURRENT_PRICE',
    # 'DAI': 'CURRENT_PRICE',
    'BCH': 'CURRENT_PRICE',
    'BTG': 'CURRENT_PRICE',
    'TUSD': 'CURRENT_PRICE',
    'PAX': 'CURRENT_PRICE',
    'XEM': 'CURRENT_PRICE',
    'REP': 'CURRENT_PRICE',
    'NEO': 'CURRENT_PRICE',
    'EOS': 'CURRENT_PRICE',
    #'LSK': 'CURRENT_PRICE',
    'ADA': 'CURRENT_PRICE',
    'WAVES': 'CURRENT_PRICE',
    'OMG': 'CURRENT_PRICE',
    'XVG': 'CURRENT_PRICE',
    'ZRX': 'CURRENT_PRICE',
    'ICX': 'CURRENT_PRICE',
    'KMD': 'CURRENT_PRICE',
    'BTT': 'CURRENT_PRICE',
    'BAT': 'CURRENT_PRICE',
    'ONT': 'CURRENT_PRICE',
    'LINK': 'CURRENT_PRICE',
    'ATOM': 'CURRENT_PRICE',
    'XTZ': 'CURRENT_PRICE',
    'UNI': 'CURRENT_PRICE',
    'RVN': 'CURRENT_PRICE',
    'SOL': 'CURRENT_PRICE',
    'VET': 'CURRENT_PRICE',
    'ETH': 'CURRENT_PRICE',
    'TRX': 'CURRENT_PRICE',
    'BNB': 'CURRENT_PRICE',
    'USDT': 'CURRENT_PRICE'
}

bestchange_links = {
    "QIWI RUB": {
        'XMR': "https://www.bestchange.net/qiwi-to-monero.html",
        'BTC': "https://www.bestchange.net/qiwi-to-bitcoin.html",
        'LTC': "https://www.bestchange.net/qiwi-to-litecoin.html",
        'XLM': "https://www.bestchange.net/qiwi-to-stellar.html",
        'ETC': "https://www.bestchange.net/qiwi-to-ethereum-classic.html",
        'ZEC': "https://www.bestchange.net/qiwi-to-zcash.html",
        'DOT': "https://www.bestchange.net/qiwi-to-polkadot.html",
        'QTUM': "https://www.bestchange.net/qiwi-to-qtum.html",
        'BUSD': "https://www.bestchange.net/qiwi-to-busd.html",
        'DASH': "https://www.bestchange.net/qiwi-to-dash.html",
        'DOGE': 'https://www.bestchange.net/qiwi-to-dogecoin.html',
        # 'DAI': 'https://www.bestchange.net/qiwi-to-dai.html',
        'BCH': 'https://www.bestchange.net/qiwi-to-bitcoin-cash.html',
        'BTG': 'https://www.bestchange.net/qiwi-to-bitcoin-gold.html',
        'TUSD': 'https://www.bestchange.net/qiwi-to-trueusd.html',
        'PAX': 'https://www.bestchange.net/qiwi-to-paxos.html',
        'XEM': 'https://www.bestchange.net/qiwi-to-nem.html',
        'REP': 'https://www.bestchange.net/qiwi-to-augur.html',
        'NEO': 'https://www.bestchange.net/qiwi-to-neo.html',
        'EOS': 'https://www.bestchange.net/qiwi-to-eos.html',
        #'LSK': 'https://www.bestchange.net/qiwi-to-lisk.html',
        'ADA': 'https://www.bestchange.net/qiwi-to-cardano.html',
        'WAVES': 'https://www.bestchange.net/qiwi-to-waves.html',
        'OMG': 'https://www.bestchange.net/qiwi-to-omg.html',
        'XVG': 'https://www.bestchange.net/qiwi-to-verge.html',
        'ZRX': 'https://www.bestchange.net/qiwi-to-zrx.html',
        'ICX': 'https://www.bestchange.net/qiwi-to-icon.html',
        'KMD': 'https://www.bestchange.net/qiwi-to-komodo.html',
        'BTT': 'https://www.bestchange.net/qiwi-to-bittorrent.html',
        'BAT': 'https://www.bestchange.net/qiwi-to-bat.html',
        'ONT': 'https://www.bestchange.net/qiwi-to-ontology.html',
        'LINK': 'https://www.bestchange.net/qiwi-to-chainlink.html',
        'ATOM': 'https://www.bestchange.net/qiwi-to-cosmos.html',
        'XTZ': 'https://www.bestchange.net/qiwi-to-tezos.html',
        'UNI': 'https://www.bestchange.net/qiwi-to-uniswap.html',
        'RVN': 'https://www.bestchange.net/qiwi-to-ravencoin.html',
        'SOL': 'https://www.bestchange.net/qiwi-to-solana.html',
        'VET': 'https://www.bestchange.net/qiwi-to-vechain.html',
        'ETH': 'https://www.bestchange.net/qiwi-to-ethereum.html',
        'TRX': 'https://www.bestchange.net/qiwi-to-tron.html',
        'BNB': 'https://www.bestchange.net/qiwi-to-binance-coin.html'
    },
    "Тинькофф RUB": {
        'XMR': "https://www.bestchange.net/tinkoff-to-monero.html",
        'BTC': "https://www.bestchange.net/tinkoff-to-bitcoin.html",
        'LTC': "https://www.bestchange.net/tinkoff-to-litecoin.html",
        'XLM': "https://www.bestchange.net/tinkoff-to-stellar.html",
        'ETC': "https://www.bestchange.net/tinkoff-to-ethereum-classic.html",
        'ZEC': "https://www.bestchange.net/tinkoff-to-zcash.html",
        'DOT': "https://www.bestchange.net/tinkoff-to-polkadot.html",
        'QTUM': "https://www.bestchange.net/tinkoff-to-qtum.html",
        'BUSD': "https://www.bestchange.net/tinkoff-to-busd.html",
        'DASH': "https://www.bestchange.net/tinkoff-to-dash.html",
        'DOGE': 'https://www.bestchange.net/tinkoff-to-dogecoin.html',
        # 'DAI': 'https://www.bestchange.net/tinkoff-to-dai.html',
        'BCH': 'https://www.bestchange.net/tinkoff-to-bitcoin-cash.html',
        'BTG': 'https://www.bestchange.net/tinkoff-to-bitcoin-gold.html',
        'TUSD': 'https://www.bestchange.net/tinkoff-to-trueusd.html',
        'PAX': 'https://www.bestchange.net/tinkoff-to-paxos.html',
        'XEM': 'https://www.bestchange.net/tinkoff-to-nem.html',
        'REP': 'https://www.bestchange.net/tinkoff-to-augur.html',
        'NEO': 'https://www.bestchange.net/tinkoff-to-neo.html',
        'EOS': 'https://www.bestchange.net/tinkoff-to-eos.html',
        #'LSK': 'https://www.bestchange.net/tinkoff-to-lisk.html',
        'ADA': 'https://www.bestchange.net/tinkoff-to-cardano.html',
        'WAVES': 'https://www.bestchange.net/tinkoff-to-waves.html',
        'OMG': 'https://www.bestchange.net/tinkoff-to-omg.html',
        'XVG': 'https://www.bestchange.net/tinkoff-to-verge.html',
        'ZRX': 'https://www.bestchange.net/tinkoff-to-zrx.html',
        'ICX': 'https://www.bestchange.net/tinkoff-to-icon.html',
        'KMD': 'https://www.bestchange.net/tinkoff-to-komodo.html',
        'BTT': 'https://www.bestchange.net/tinkoff-to-bittorrent.html',
        'BAT': 'https://www.bestchange.net/tinkoff-to-bat.html',
        'ONT': 'https://www.bestchange.net/tinkoff-to-ontology.html',
        'LINK': 'https://www.bestchange.net/tinkoff-to-chainlink.html',
        'ATOM': 'https://www.bestchange.net/tinkoff-to-cosmos.html',
        'XTZ': 'https://www.bestchange.net/tinkoff-to-tezos.html',
        'UNI': 'https://www.bestchange.net/tinkoff-to-uniswap.html',
        'RVN': 'https://www.bestchange.net/tinkoff-to-ravencoin.html',
        'SOL': 'https://www.bestchange.net/tinkoff-to-solana.html',
        'VET': 'https://www.bestchange.net/tinkoff-to-vechain.html',
        'ETH': 'https://www.bestchange.net/tinkoff-to-ethereum.html',
        'TRX': 'https://www.bestchange.net/tinkoff-to-tron.html',
        'BNB': 'https://www.bestchange.net/tinkoff-to-binance-coin.html'
    },
    "Сбербанк RUB": {
        'XMR': "https://www.bestchange.net/sberbank-to-monero.html",
        'BTC': "https://www.bestchange.net/sberbank-to-bitcoin.html",
        'LTC': "https://www.bestchange.net/sberbank-to-litecoin.html",
        'XLM': "https://www.bestchange.net/sberbank-to-stellar.html",
        'ETC': "https://www.bestchange.net/sberbank-to-ethereum-classic.html",
        'ZEC': "https://www.bestchange.net/sberbank-to-zcash.html",
        'DOT': "https://www.bestchange.net/sberbank-to-polkadot.html",
        'QTUM': "https://www.bestchange.net/sberbank-to-qtum.html",
        'BUSD': "https://www.bestchange.net/sberbank-to-busd.html",
        'DASH': "https://www.bestchange.net/sberbank-to-dash.html",
        'DOGE': 'https://www.bestchange.net/sberbank-to-dogecoin.html',
        # 'DAI': 'https://www.bestchange.net/sberbank-to-dai.html',
        'BCH': 'https://www.bestchange.net/sberbank-to-bitcoin-cash.html',
        'BTG': 'https://www.bestchange.net/sberbank-to-bitcoin-gold.html',
        'TUSD': 'https://www.bestchange.net/sberbank-to-trueusd.html',
        'PAX': 'https://www.bestchange.net/sberbank-to-paxos.html',
        'XEM': 'https://www.bestchange.net/sberbank-to-nem.html',
        'REP': 'https://www.bestchange.net/sberbank-to-augur.html',
        'NEO': 'https://www.bestchange.net/sberbank-to-neo.html',
        'EOS': 'https://www.bestchange.net/sberbank-to-eos.html',
        #'LSK': 'https://www.bestchange.net/sberbank-to-lisk.html',
        'ADA': 'https://www.bestchange.net/sberbank-to-cardano.html',
        'WAVES': 'https://www.bestchange.net/sberbank-to-waves.html',
        'OMG': 'https://www.bestchange.net/sberbank-to-omg.html',
        'XVG': 'https://www.bestchange.net/sberbank-to-verge.html',
        'ZRX': 'https://www.bestchange.net/sberbank-to-zrx.html',
        'ICX': 'https://www.bestchange.net/sberbank-to-icon.html',
        'KMD': 'https://www.bestchange.net/sberbank-to-komodo.html',
        'BTT': 'https://www.bestchange.net/sberbank-to-bittorrent.html',
        'BAT': 'https://www.bestchange.net/sberbank-to-bat.html',
        'ONT': 'https://www.bestchange.net/sberbank-to-ontology.html',
        'LINK': 'https://www.bestchange.net/sberbank-to-chainlink.html',
        'ATOM': 'https://www.bestchange.net/sberbank-to-cosmos.html',
        'XTZ': 'https://www.bestchange.net/sberbank-to-tezos.html',
        'UNI': 'https://www.bestchange.net/sberbank-to-uniswap.html',
        'RVN': 'https://www.bestchange.net/sberbank-to-ravencoin.html',
        'SOL': 'https://www.bestchange.net/sberbank-to-solana.html',
        'VET': 'https://www.bestchange.net/sberbank-to-vechain.html',
        'ETH': 'https://www.bestchange.net/sberbank-to-ethereum.html',
        'TRX': 'https://www.bestchange.net/sberbank-to-tron.html',
        'BNB': 'https://www.bestchange.net/sberbank-to-binance-coin.html'
    }
}

binance_links = {
    'XMR': 'https://www.binance.com/ru/trade/XMR_USDT?layout=pro&theme=dark&type=spot',
    'BTC': 'https://www.binance.com/ru/trade/BTC_USDT?layout=pro&theme=dark&type=spot',
    'LTC': 'https://www.binance.com/ru/trade/LTC_USDT?layout=pro&theme=dark&type=spot',
    'XLM': 'https://www.binance.com/ru/trade/XLM_USDT?layout=pro&theme=dark&type=spot',
    'ETC': 'https://www.binance.com/ru/trade/ETC_USDT?layout=pro&theme=dark&type=spot',
    'ZEC': 'https://www.binance.com/ru/trade/ZEC_USDT?layout=pro&theme=dark&type=spot',
    'DOT': 'https://www.binance.com/ru/trade/DOT_USDT?layout=pro&theme=dark&type=spot',
    'QTUM': 'https://www.binance.com/ru/trade/QTUM_USDT?layout=pro&theme=dark&type=spot',
    'BUSD': 'https://www.binance.com/ru/trade/BUSD_USDT?layout=pro&theme=dark&type=spot',
    'DASH': 'https://www.binance.com/ru/trade/DASH_USDT?layout=pro&theme=dark&type=spot',
    'DOGE': 'https://www.binance.com/ru/trade/DOGE_USDT?layout=pro&theme=dark&type=spot',
    # 'DAI': 'https://www.binance.com/ru/trade/DAI_USDT?layout=pro&theme=dark&type=spot',
    'BCH': 'https://www.binance.com/ru/trade/BCH_USDT?layout=pro&theme=dark&type=spot',
    'BTG': 'https://www.binance.com/ru/trade/BTG_USDT?layout=pro&theme=dark&type=spot',
    'TUSD': 'https://www.binance.com/ru/trade/TUSD_USDT?layout=pro&theme=dark&type=spot',
    'PAX': 'https://www.binance.com/ru/trade/PAX_USDT?layout=pro&theme=dark&type=spot',
    'XEM': 'https://www.binance.com/ru/trade/XEM_USDT?layout=pro&theme=dark&type=spot',
    'REP': 'https://www.binance.com/ru/trade/REP_USDT?layout=pro&theme=dark&type=spot',
    'NEO': 'https://www.binance.com/ru/trade/NEO_USDT?layout=pro&theme=dark&type=spot',
    'EOS': 'https://www.binance.com/ru/trade/EOS_USDT?layout=pro&theme=dark&type=spot',
    #'LSK': 'https://www.binance.com/ru/trade/LSK_USDT?layout=pro&theme=dark&type=spot',
    'ADA': 'https://www.binance.com/ru/trade/ADA_USDT?layout=pro&theme=dark&type=spot',
    'WAVES': 'https://www.binance.com/ru/trade/WAVES_USDT?layout=pro&theme=dark&type=spot',
    'OMG': 'https://www.binance.com/ru/trade/OMG_USDT?layout=pro&theme=dark&type=spot',
    'XVG': 'https://www.binance.com/ru/trade/XVG_USDT?layout=pro&theme=dark&type=spot',
    'ZRX': 'https://www.binance.com/ru/trade/ZRX_USDT?layout=pro&theme=dark&type=spot',
    'ICX': 'https://www.binance.com/ru/trade/ICX_USDT?layout=pro&theme=dark&type=spot',
    'KMD': 'https://www.binance.com/ru/trade/KMD_USDT?layout=pro&theme=dark&type=spot',
    'BTT': 'https://www.binance.com/ru/trade/BTT_USDT?layout=pro&theme=dark&type=spot',
    'BAT': 'https://www.binance.com/ru/trade/BAT_USDT?layout=pro&theme=dark&type=spot',
    'ONT': 'https://www.binance.com/ru/trade/ONT_USDT?layout=pro&theme=dark&type=spot',
    'LINK': 'https://www.binance.com/ru/trade/LINK_USDT?layout=pro&theme=dark&type=spot',
    'ATOM': 'https://www.binance.com/ru/trade/ATOM_USDT?layout=pro&theme=dark&type=spot',
    'XTZ': 'https://www.binance.com/ru/trade/XTZ_USDT?layout=pro&theme=dark&type=spot',
    'UNI': 'https://www.binance.com/ru/trade/UNI_USDT?layout=pro&theme=dark&type=spot',
    'RVN': 'https://www.binance.com/ru/trade/RVN_USDT?layout=pro&theme=dark&type=spot',
    'SOL': 'https://www.binance.com/ru/trade/SOL_USDT?layout=pro&theme=dark&type=spot',
    'VET': 'https://www.binance.com/ru/trade/VET_USDT?layout=pro&theme=dark&type=spot',
    'ETH': 'https://www.binance.com/ru/trade/ETH_USDT?layout=pro&theme=dark&type=spot',
    'TRX': 'https://www.binance.com/ru/trade/TRX_USDT?layout=pro&theme=dark&type=spot',
    'BNB': 'https://www.binance.com/ru/trade/BNB_USDT?layout=pro&theme=dark&type=spot',
    'USDT': 'https://www.binance.com/ru/trade/USDT_RUB?layout=pro&theme=dark&type=spot'
}

telegram_bot_token = '1936049354:AAHs69sW1m7vzP9n43SZ6ovC_eJlIDhWNJE'
channel_chat_id_plus1 = '-1001571027081'
channel_chat_id_under1 = '-1001591167204'
